### ISSUE TITLE
Place for user to submit text

### ISSUE THREAD

**Issue by bkojusner** [Archana90663/New_PasteBin#2]
Create Angular page where a user can:
- [x] Paste text into a text box
- [x] Find library that allows to format text with text editor options
- [x] Submit text with submit button

Resolves part of the user story #1

**Comment by paramgupta107** [comment]
For our text box, we need to find an open-source version of something like this 
https://ej2.syncfusion.com/angular/demos/?_ga=2.207022928.2108385970.1643140422-333744874.1643140422#/material/rich-text-editor/tools
I have used open-source libraries like this but am not aware of any for angular (need to look).
However, one downside of this kind of approach is that it formats the text using HTML. So we will have to display user-submitted HTML(vulnerable to XSS attacks if not handled properly)

Another approach is formatting text using markdown. 
here is an example:-
https://codepen.io/cusx/pen/mJNKre

Ideally, if we can find a library that can create a text box like https://stackedit.io/app# then it would be perfect.
A text box like text box for writing comments here on github is what I think would be best.
