### ISSUE TITLE
Ensure only "Unlisted" pastes can be shared

### ISSUE THREAD

**Issue by Archana90663** [Archana90663/New_PasteBin#203]
Generate a separate URL/link for a specific unlisted post so that it can be shared. Ensure this doesn't work for private pastes. An example could be "localhost:4200/pastes/[pasteID]" which if given the link to someone else, they should be able to see that paste.

Check for comments made by @paramgupta107 for more details

**Comment by paramgupta107** [comment]
URL/link system already exists. The case that will have to be handled is when the user opens the link for a paste and the backend returns HTTP error code 401.

**Comment by paramgupta107** [comment]
> URL/link system already exists. The case that will have to be handled is when the user opens the link for a paste and the backend returns HTTP error code 401.

refer the documentation [here](https://github.com/Archana90663/New_PasteBin/wiki/Get-Text-Route)
