### ISSUE TITLE
Send request to test route from front-end to back-end.

### ISSUE THREAD

**Issue by paramgupta107** [Archana90663/New_PasteBin#24]
There is a sample route that will run on localhost:8080
Make a test page that will send a request to the test route and get the sample data to test the connection between the front-end and backend.
`
make run
` can be used to run the front-end and backend together for testing. This will run the front-end on port 4200 and the backend on port 8080.
`
make build
` will create a standalone executable in the Server directory. This executable will have both front-end and backend in it. Running this executable will be enough to run the entire system. Note:- When we run this executable, the front-end homepage will be available at localhost:8080. Also, make sure to terminate anything that is already running using `make run`.

route:
```
GET /test
```
Content-Type:
```
application/json
```
response types:
```
type Response struct {
	persons []Person
}
```
```
type Person struct {
	id int
	first_name string
	last_name  string
}
```
sample response:
```
{"persons":[{"id":1,"first_name":"fn","last_name":"ln"},{"id":10,"first_name":"Issac","last_name":"Newton"},{"id":22,"first_name":"Albert","last_name":"Einstein"}]}

**Comment by bkojusner** [comment]
@Archana90663 and myself just got the back-end code to compile and run as an executable. Looking at how to extract data from the route to display on the front-end.
