### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by bkojusner** [Archana90663/New_PasteBin#331]
README in the Main repository needs to be updated to include information required for the project submission. Below is a checklist of the information that needs to either be added or updated in the README. This can be resolved by multiple members making partial commits to main from their branch.

- [x] Description of your application - 200 words max
- [x] Demo video functionality - 3min max
- [x] Cypress test video - 90sec max
- [x] Backend unit test video - 90sec max
- [x] Link to API Documentation
- [x] Link to Project board
- [x] Link to Sprint4 deliverables
- [x] Frontend and backend team members

Note: Videos need to be embedded in the README instead of being externally linked to another website.

**Comment by Archana90663** [comment]
Front and back end team members were already updated so just checking that box.

**Comment by bkojusner** [comment]
Sprint 4 deliverables were already added in the README
