### ISSUE TITLE
Cypress Test: Viewpage component

### ISSUE THREAD

**Issue by Archana90663** [Archana90663/New_PasteBin#358]
Since it's the last sprint, add more Cypress tests to assess if everything is working correctly in this component. Examples could include: checking for null values, if user is logged in, functionalities that logged in user can do vs. anonymous users, paste userID is correct, and many more.

**Comment by bkojusner** [comment]
Tried to login again when testing via Cypress but the login window returns errors this time about insecure login with social account. I set up the proper authentication measures using the Google account API process and connected it with Cypress however the program still does not work. Tried the same solution as Sprint3 and once more it failed. This might be an infrastructure limitation or requires some additional connection/implementation to connect the back-end API route. Tried doing more research on it but can't find a solution on StackOverflow or Angular documentation. Closing this issue and other ones that require user to be logged in.
