### ISSUE TITLE
Cypress Test: Loginpage component

### ISSUE THREAD

**Issue by Archana90663** [Archana90663/New_PasteBin#359]
Since it's the last sprint, add more Cypress tests to assess if everything is working correctly in this component. Examples could include: checking for null values, if user is logged in, functionalities that logged in user can do vs. anonymous users, paste userID is correct, and many more.

**Comment by bkojusner** [comment]
Login was thoroughly tested in Sprint3. The files that do this are `social_login_spec.js` and `logging_out_spec.js`. Closing this issue off since no new features were added to the Login front-end.
