### ISSUE TITLE
Storing the metadata in database

### ISSUE THREAD

**Issue by Archana90663** [Archana90663/New_PasteBin#6]
When a text/file is submitted, store its metadata in the database.

**Comment by SudhanshuTarale** [comment]
For storing metadata, we will have to first decide upon the parameters that we will send to the backend and thereby also discuss what tables we will need in our database

**Comment by paramgupta107** [comment]
> For storing metadata, we will have to first decide upon the parameters that we will send to the backend and thereby also discuss what tables we will need in our database

@SudhanshuTarale Tables will be automatically created and managed by Gorm. See how texts are currently stored in db. Let me know what metadata fields you think are appropriate.

**Comment by SudhanshuTarale** [comment]
@paramgupta107 metadata about the post should contain created_at (already present), expiry (we could ask the user for this or set a default), type of post (when we recognize a post as let's say Java, Python, etc. we can store that post with the tag of "Coding" and so on for the different type of posts), maybe password for a post (in a later sprint)
Type of Post will let us also display the top 5 posts of that category on our homepage.

In case we don't want to recognize a type of post, we can just ask the user to put a tag on it. Like the tags we add for our issues.

**Comment by paramgupta107** [comment]
> @paramgupta107 metadata about the post should contain created_at (already present), expiry (we could ask the user for this or set a default), type of post (when we recognize a post as let's say Java, Python, etc. we can store that post with the tag of "Coding" and so on for the different type of posts), maybe password for a post (in a later sprint) Type of Post will let us also display the top 5 posts of that category on our homepage.
> 
> In case we don't want to recognize a type of post, we can just ask the user to put a tag on it. Like the tags we add for our issues.

For now just store created_at (already present), length of text, IP of user, location of IP(use a library for this)
