### ISSUE TITLE
Submit text

### ISSUE THREAD

**Issue by paramgupta107** [Archana90663/New_PasteBin#61]
When a user presses the submit button on the submit page, a post request should be made to the route `/api/submitText`. Details of the route are in the wiki.

**Comment by paramgupta107** [comment]
Also, ensure title(to be made in #62 ) is also sent in the post request

**Comment by paramgupta107** [comment]
Also, ensure the expiration date(to be made in #64 ) is also sent in the post request

**Comment by bkojusner** [comment]
Been working on this today. Running into issues with CORS policy. Referring to [this](https://stackoverflow.com/questions/56328474/origin-http-localhost4200-has-been-blocked-by-cors-policy-in-angular7) for assistance.

**Comment by paramgupta107** [comment]
> Been working on this today. Running into issues with CORS policy. Referring to [this](https://stackoverflow.com/questions/56328474/origin-http-localhost4200-has-been-blocked-by-cors-policy-in-angular7) for assistance.

did enable CORS in #52 
Will have to debug what the issue is
